versio
services:
  db:
    build:
      context: .
      dockerfile: db.Dockerfile
    container_name: deberts-database
    environment:
      - POSTGRES_PASSWORD=nhk123
    ports:
      - "5432:5432"
  web:
    build:
      context: .
      dockerfile: web.Dockerfile
    container_name: deberts
    ports:
      - "8080:8080"
